#!/bin/sh

#calculate LOC
find . -name "*.h" |xargs wc -l
find . -name "*.cpp" | xargs wc -l

#use path according to boost installation directory in user machine
export LD_LIBRARY_PATH=/home/aftab/Downloads/boost_1.62_installed/lib:$LD_LIBRARY_PATH
#export LD_LIBRARY_PATH=/home/cloud/aftab/Downloads/boost_1.62_installed/lib:$LD_LIBRARY_PATH

GRAPHFILE=$1
GRAMMAR=$2
NUMPARTITIONS=$3
MEMBUDGET=$4
NUMTHREADS=$5
DATASTRUCTURE="array"
#DATASTRUCTURE="list"
#DATASTRUCTURE="array2"

echo "DiskSpa running..."
logFile="log/$3.$4.$5.output"
#valgrind --max-stackframe=3599608 ../bin/comp $1 $2 $3 $4 $5 $DATASTRUCTURE
../bin/comp $1 $2 $3 $4 $5 $DATASTRUCTURE
echo "DiskSpa finished"
