#!/bin/sh

#calculate LOC
#find . -name "*.h" |xargs wc -l
#find . -name "*.cpp" | xargs wc -l

#use path according to boost installation directory in user machine
export LD_LIBRARY_PATH=/home/aftab/Downloads/boost_1.62_installed/lib:$LD_LIBRARY_PATH

GRAPHFILE=$1
GRAMMAR=$2
NUMPARTITIONS=$3
MEMBUDGET=$4
NUMTHREADS=$5
DATASTRUCTURE=$6

rm *.part

echo "DiskSpa running..."
../bin/comp $1 $2 $3 $4 $5 $6
echo "DiskSpa finished"
